language: emacs-lisp
os: osx
osx_image: xcode9.3
env:
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25.3
  - EMACS_VERSION=snapshot
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
cache:
  directories:
    - .cask
before_install:
  - export PATH="${HOME}/bin:${PATH}"
  # - export EMACSCONFFLAGS='--without-all --with-x-toolkit=no --with-xml2 --without-toolkit-scroll-bars --without-ns --without-x'
  # - export CFLAGS='-O2 -march=native'
  # - export CXXFLAGS='-O2 -march=native'
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  - emacs --version
script:
  - make test
notifications:
  slack:
    secure: WG3LccTCFtC1IvznaCMJhoX46DuPuTyEI9FVmB5LMFcv+m8O8Q0Wxb83r/6veFqyypmRfgkiBRb5O7lfanc15sBXI7iUs4kw8nsRiVSAPemX00QNzi+pgYfwHgoI7dZzMfxPMKpzuxpuhVO8cv/T/7NizE5TntnLIlcgDRch5RpcvfJJ4zQN0mVFBGnaXmVi1SEHeSNZ3XzcXHVUc4S2rGCJUf9XzDRzjN7JPo7Sp182JfQ3fwquxMoNSsXZLIrioz9naTNcjrF5vARQ+KpsN8e+hJyD7eKwNaItUGFen2RuIAGwr5eW1xOqlN7pmpa5eaEipjwAOLYV4mEFZlWRcUNQoA9H82vkaZv8A6HVOJ2Fzx2mn/flZK3rnk6lrLYsm9uqjPpsl0OaXduWuVIRvUHUXSOz81++4R3EuN5guC6xCu++G7UWq9Vee1Ziyib8eXo7A1TEKCcY+enpTRufqkVRJykzmfd/GdGj0OqcmAO03LmDZnMqtfHD6gZeNwE8bZNKEDriWJSK6cSGeq2IpoBDOJPzF9/D725sQrRSNuvbZmI1Roa9oh/FGhTFJ5zFpiXhA8ainP7p745UjN56DCUocR+7NTHMEuFtY56RIcn2M1MncwsWO1GEUz6gY9Bwh6qmDJ9Tvs55IMfOnG4dtVFClfCvtvhq6UHUItirWeQ=
